### ISSUE TITLE
Labyrintherstellung und -lösung

### ISSUE THREAD

**Issue by obcode** [ob-algdatii-ss19/ob-algdatii-ss19#1]
Sie können sich ja mal kurzschließen, ob die Gruppe Labyrinthlösung als Eingabe das Ergebnis der Gruppe Labyrintherstellung nimmt.

**Comment by maxiking203** [comment]
Unsere Labyrinthe könnten wir auf jeden Fall in Form der entprechenden Adjazenzmatrix zur Verfügung stellen.

**Comment by ghost** [comment]
Beispiel-Output zum Experimentieren: Dieses 3x3-Labyrinth, erstellt durch den Backtracking-Algorithmus ...

`[[1 1 0 0 0 0 0 0 0] [1 1 0 0 1 0 0 0 0] [0 0 1 0 0 1 0 0 0] [0 0 0 1 0 0 1 0 0] [0 1 0 0 1 1 0 0 0] [0 0 1 0 1 1 0 0 1] [0 0 0 1 0 0 1 1 0] [0 0 0 0 0 0 1 1 1] [0 0 0 0 0 1 0 1 1]]`

... kann man z.B. so darstellen:

![Labyrinth-Beispiel](https://i.imgur.com/MV8wy7C.png)

**Comment by ghost** [comment]
Das entspricht sicherlich den Erwartungen, aber um das Format für den Austausch schriftlich zu haben:

- Wir gehen zur Erstellung der Indices in der Adjazenzmatrix **zeilenweise von links nach rechts** vor.
- Formel: **Index = Y * AnzahlSpalten + X**
- Also ist **[0][1]** (und entsprechend [1][0]) die Beziehung vom Feld _oben links_ mit seinem _rechten Nachbarn_.
- **[0][3]** (und [3][0]) wäre bei drei Feldern pro Zeile dann die Beziehung vom Feld _oben links_ mit seinem _unteren Nachbarn_.
- Ein Adjazenzmatrix-Eintrag von **0** heißt keine Verbindung (i.e. "_Wand_"), **1** bedeutet eine Verbindung ("_keine Wand_").

**Comment by salman2893** [comment]
Ok danke, dann werde den Input für meine Anwendung entsprechend gestalten.

**Comment by obcode** [comment]
Sie haben ja alle Adminrechte in Ihren Repos. Sie können sich also, wenn Sie wollen, gegenseitig Leserechte geben oder so...

**Comment by ghost** [comment]
Ja, wenn das erlaubt ist, umso besser.
Salman, du solltest jetzt Lesezugriff auf unser Repo haben.

Die Version auf dem Develop-Branch ist lauffähig.
Aktuelle Dokumentation ist im Readme im Branch _gh-pages_.
Viel Vergnügen :)

**Comment by obcode** [comment]
na logo ist das erlaubt.
